### ISSUE TITLE
Translation Manager not showing any data

### ISSUE THREAD

**Issue by kay899** [hpolthof/laravel-translations-db#1]
I installed the translation manager packages as described.
But when I go to .../_translations the DropDowns are empty.
Even when I do "php artisan translation:fetch" it still stays empty.
My standard locale is "de" and my fallback_locale is "en".

Any idea what is going wrong?
Thanks
kay899

**Comment by hpolthof** [comment]
Are there any translations in your database yet?

**Comment by kay899** [comment]
No, database is totally empty

**Comment by hpolthof** [comment]
That might be the problem. You should first run the migration. After running the migration the database will fill itself with all locales you've already in your project. Every time Lang::get or trans() is called the value will be added.

Does this help you?

**Comment by kay899** [comment]
Hi, yes this helped. I now have understood how this is working.
One other question: the import of keys via shell is now working at all with
"php artisan translation:fetch"
My default language is "de", could that cause any problems with that?

**Comment by hpolthof** [comment]
Your default language is not of any influence. By default the fetch function will just traverse through all language files of all locales and index them based on the language directory their in.
