### ISSUE TITLE
Laravel 5.3 lists not exists

### ISSUE THREAD

**Issue by luukverhoeven** [hpolthof/laravel-translations-db#14]
Lists is deprecated:

![image](https://cloud.githubusercontent.com/assets/995760/18142890/d21af092-6fbf-11e6-99e9-e6054664e805.png)

Can be fixed by this:
![image](https://cloud.githubusercontent.com/assets/995760/18142869/b09ac3b6-6fbf-11e6-8609-6eb1929e3c1c.png)

**Comment by hpolthof** [comment]
Fixed in 0.4.5
