### ISSUE TITLE
php artisan vendor:publish - Nothing to publish for tag [].

### ISSUE THREAD

**Issue by FDiskas** [hpolthof/laravel-translations-db#5]
If I run

```
php artisan vendor:publish --provider='Hpolthof\Translation\ServiceProvider'
```

I got

```
Nothing to publish for tag [].
```

**Comment by veryfoodverygood** [comment]
I got the same error when trying to debug a different problem.  I got that error when running the artisan vendor:publish command without commenting out
`//'Illuminate\Translation\TranslationServiceProvider',`
and adding
`'Hpolthof\Translation\ServiceProvider',`
in config/app.php

Have you done that step?

**Comment by veneliniliev** [comment]
php artisan vendor:publish --provider="Hpolthof\Translation\ServiceProvider"
try with double quote => "
